import { Link } from 'react-router-dom';

const productLinks = [
  { label: 'Proposal Planner', href: '/proposal' },
  { label: 'Vow Writer', href: '/vows' },
  { label: 'Love Letter', href: '/love-letter' },
  { label: 'Ring Advisor', href: '/ring-advisor' },
  { label: 'Date Ideas', href: '/date-ideas' },
];

export default function Footer() {
  return (
    <footer
      style={{
        borderTop: '1px solid var(--color-border)',
        background: '#0d0d0d',
        padding: '48px 24px 32px',
        marginTop: 'auto',
      }}
    >
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: 40,
            marginBottom: 48,
          }}
        >
          {/* Logo + tagline */}
          <div>
            <Link to="/" style={{ textDecoration: 'none' }}>
              <span
                style={{
                  fontFamily: 'var(--font-heading)',
                  fontSize: 28,
                  fontWeight: 700,
                  color: 'var(--color-rose)',
                }}
              >
                Forever
              </span>
            </Link>
            <p style={{ color: 'var(--color-muted)', fontSize: 14, marginTop: 12, lineHeight: 1.6 }}>
              Plan the moment that changes everything.
            </p>
          </div>

          {/* Product links */}
          <div>
            <p
              style={{
                fontSize: 11,
                fontWeight: 600,
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                color: 'var(--color-muted)',
                marginBottom: 16,
              }}
            >
              Tools
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {productLinks.map((link) => (
                <Link
                  key={link.href}
                  to={link.href}
                  style={{
                    textDecoration: 'none',
                    color: 'var(--color-muted)',
                    fontSize: 14,
                    transition: 'color 0.2s',
                  }}
                  onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--color-rose)')}
                  onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--color-muted)')}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          {/* About */}
          <div>
            <p
              style={{
                fontSize: 11,
                fontWeight: 600,
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                color: 'var(--color-muted)',
                marginBottom: 16,
              }}
            >
              Company
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <Link
                to="/about"
                style={{ textDecoration: 'none', color: 'var(--color-muted)', fontSize: 14, transition: 'color 0.2s' }}
                onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--color-rose)')}
                onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.color = 'var(--color-muted)')}
              >
                About &amp; Our Story
              </Link>
            </div>
          </div>
        </div>

        {/* AMD/AI Badge — prominent */}
        <div
          style={{
            background: 'linear-gradient(135deg, rgba(183,110,121,0.12), rgba(212,175,55,0.12))',
            border: '1px solid rgba(183,110,121,0.3)',
            borderRadius: 12,
            padding: '20px 24px',
            display: 'flex',
            alignItems: 'center',
            gap: 16,
            marginBottom: 32,
            flexWrap: 'wrap',
          }}
        >
          <span style={{ fontSize: 24 }}>✨</span>
          <div>
            <p
              style={{
                fontWeight: 700,
                fontSize: 15,
                color: 'var(--color-gold)',
                margin: 0,
                fontFamily: 'var(--font-heading)',
              }}
            >
              Powered by Kimi K2 on AMD Hardware via Fireworks AI
            </p>
            <p style={{ color: 'var(--color-muted)', fontSize: 13, margin: '4px 0 0', lineHeight: 1.5 }}>
              Every word generated by this app comes from Kimi K2 — an open AI model — running on AMD GPUs through the Fireworks AI API.
            </p>
          </div>
        </div>

        {/* Bottom row */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: 12,
            borderTop: '1px solid var(--color-border)',
            paddingTop: 24,
          }}
        >
          <p style={{ color: 'var(--color-muted)', fontSize: 13, margin: 0 }}>
            Built with love for{' '}
            <span style={{ color: 'var(--color-rose)' }}>AMD Developer Hackathon: ACT II</span>
          </p>
          <p style={{ color: 'var(--color-muted)', fontSize: 13, margin: 0 }}>
            For Hala. Always.
          </p>
        </div>
      </div>
    </footer>
  );
}
